### ISSUE TITLE
Update readme around `reflect` 

### ISSUE THREAD

**Issue by laduke** [zerotier/pylon#13]
Explain the reflect is a tcp-relay and how to use it. I think this is basically the same code as zerotierone/tcp-proxy. 
Then we can point people who need a proxy here. I think it's a little easier to build and release from here than from zerotierone. 
Is that ok, @joseph-henry ?

**Comment by joseph-henry** [comment]
Good idea, I cannibalized some that you wrote from the tcp-proxy page and made it into an expandable section in the reflect instructions. See: https://github.com/zerotier/pylon/commit/1c943e117d2a57fc44bf84e937567aa9205d4360

**Comment by laduke** [comment]
good idea. i forgot about that and was going to write from scratch 🚀
